# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

name: Matthias Schmidtblaicher
title: Matthias Schmidtblaicher
description: >- # this means to ignore newlines until "baseurl:"
  Personal website of Matthias Schmidtblaicher.
baseurl: "" # the subpath of the site
url: "https://mschmidtblaicher.github.io/" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: ""
include: ["_pages"]
disqus: ""
permalink: /:title/

header:
  pages:
    - name: Home
      slug: /
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: mschmidtblaicher@gmail.com
      link: mailto:mschmidtblaicher@gmail.com

  follow:
    - name: Twitter
      link: https://twitter.com/mschmidtbl
      username: "@mschmidtbl"
    - name: LinkedIn
      link: https://www.linkedin.com/in/matthias-schmidtblaicher-35270526/
    - name: GitHub
      link: https://github.com/mschmidtblaicher/mschmidtblaicher.github.io

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
